apiVersion: v1
kind: Service
metadata:
  name: flask-example-service
spec:
  selector:
    app: flask-example
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 5555
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-example
    spec:
      containers:
      - name: flask-example
        image: atoserik/flask-kube-example:httpwq!
        ports:
        - containerPort: 5555
